
# the name of Camel
camel:  
  springboot:
    name: fuseInitializer
    # route-controller-supervise-enabled: true
  component:
    kafka: 
      configuration: 
          client-id: archetype-test
          brokers: localhost:9092
  health:
    enabled: true
    indicator:
      enabled: true
    check:
      routes:
        enabled: true
server:
  address: 0.0.0.0
  port: 8585

# to automatic shutdown the JVM after a period of time
#camel.springboot.duration-max-seconds=60
#camel.springboot.duration-max-messages=100

# add for example: &repeatCount=5 to the timer endpoint to make Camel idle
#camel.springboot.duration-max-idle-seconds=15
#management.endpoints.web.exposure.include

# expose actuator endpoint via HTTP
management:
  server:
    port: 10001
    address: 0.0.0.0
  info:
    camel:
      enabled: true
  endpoints:
    hawtio:
      enabled: true
    jolokia: 
      enabled: true
    health: 
      enabled: true
    web:
      exposure:
        include: health,camelroutes,howtio,jolokia
spring:
  jmx:
    enabled: true 
hawtio:
  authenticationEnabled: false

### KAFKA
kafka:
  brokers: localhost:9092
  #brokers: ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_BROKERS:sdr01kbr01.uscc.com:9093,sdr01kbr02.uscc.com:9093,sdr02kbr03.uscc.com:9093,sdr02kbr04.uscc.com:9093}
  saslJaasConfig:
    kerberos: 
      keytabfile:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_SASL_JAAS_CONFIG_KERBEROS_KEYTABFILE:svc_kafka_isint_nprd.keytab}
      principal:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_SASL_JAAS_CONFIG_KERBEROS_PRINCIPAL:svc_kafka_isint_nprd@INT.USC.LOCAL}
      krb5:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_SASL_JAAS_CONFIG_KERBEROS_KRB5=krb5.conf}
  saslKerberosServiceName:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_SASL_KERBEROS_SERVICE_NAME:kafka}
  thread: 
    pool:
      size:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_THREAD_POOL_SIZE:100}
      max:
        size:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_MAX_THREAD_POOL_SIZE:200}
  topic:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_TOPIC:webcheck-notification_events-dev01}
  publisher.clientId:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_PUBLISHER_CLIENTID:order-details-event-listener-v1-0-publisher}
  max:
    block: 
      ms:  ${ORDER_DETAILS_EVENT_LISTENER_KAFKA_MAX_BLOCK_MS:30000}

### SSL
# SSL trust store password and key store file name for provider service

ssl:
  truststore:
    secrets-path: ${ORDER_DETAILS_EVENT_LISTENER_BACKEND_SSL_TRUST_STORE_SECRETS_PATH:src/main/resources/keystore}
#Truststore
    jks-file: ${ORDER_DETAILS_EVENT_LISTENER_CXF_SSL_TRUST_STORE_JKS_FILE:trust_store.jks}
    jks-file-password: ${ORDER_DETAILS_EVENT_LISTENER_CXF_SSL_TRUST_STORE_JKS_FILE_PASSWORD:jeqxqI6ECpo2Ju5KQFQA}
#Identity
  identitystore:
    jks-file: ${ORDER_DETAILS_EVENT_LISTENER_CXF_SSL_IDENTITY_STORE_JKS_FILE:identity_store.jks}
    jks-file-password: ${ORDER_DETAILS_EVENT_LISTENER_CXF_SSL_IDENTITY_STORE_JKS_FILE_PASSWORD:qeFviXlfXWvSOmhZqQf7}
  
backend:
  service:
    name: ${ORDER_DETAILS_EVENT_LISTENER_CONSTANT_BACKEND_SERVICE_NAME:backendServiceName}

notification:
  type: 
    sms:
      value:  ${ORDER_DETAILS_EVENT_LISTENER_CONSTANT_SMS_NOTIFICATION_TYPE:CRETVSIMS001}
      activity-type: ${ORDER_DETAILS_EVENT_LISTENER_CONSTANT_SMS_NOTIFICATION_ACTIVITY_TYPE:WC_SMS_NOTIFICATION_ACTIVATION}