/*
 * Fuse Initializer
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nvasc001@uscellular.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.uscellular.service.route.entity;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MvnProperties
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-01T10:58:47.459272-03:00[America/Sao_Paulo]")
public class MvnProperties {
  @SerializedName("artifactVersion")
  private String artifactVersion = null;

  @SerializedName("artifactGroupId")
  private String artifactGroupId = null;

  @SerializedName("artifactPackage")
  private String artifactPackage = null;

  @SerializedName("artifactName")
  private String artifactName = null;

  @SerializedName("consumerType")
  private String consumerType = null;

  @SerializedName("producerType")
  private String producerType = null;

  @SerializedName("consumerSpec")
  private String consumerSpec = null;

  @SerializedName("producerSpec")
  private String producerSpec = null;

  public MvnProperties artifactVersion(String artifactVersion) {
    this.artifactVersion = artifactVersion;
    return this;
  }

   /**
   * Get artifactVersion
   * @return artifactVersion
  **/
  @Schema(required = true, description = "")
  public String getArtifactVersion() {
    return artifactVersion;
  }

  public void setArtifactVersion(String artifactVersion) {
    this.artifactVersion = artifactVersion;
  }

  public MvnProperties artifactGroupId(String artifactGroupId) {
    this.artifactGroupId = artifactGroupId;
    return this;
  }

   /**
   * Get artifactGroupId
   * @return artifactGroupId
  **/
  @Schema(required = true, description = "")
  public String getArtifactGroupId() {
    return artifactGroupId;
  }

  public void setArtifactGroupId(String artifactGroupId) {
    this.artifactGroupId = artifactGroupId;
  }

  public MvnProperties artifactPackage(String artifactPackage) {
    this.artifactPackage = artifactPackage;
    return this;
  }

   /**
   * Get artifactPackage
   * @return artifactPackage
  **/
  @Schema(required = true, description = "")
  public String getArtifactPackage() {
    return artifactPackage;
  }

  public void setArtifactPackage(String artifactPackage) {
    this.artifactPackage = artifactPackage;
  }

  public MvnProperties artifactName(String artifactName) {
    this.artifactName = artifactName;
    return this;
  }

   /**
   * Get artifactName
   * @return artifactName
  **/
  @Schema(required = true, description = "")
  public String getArtifactName() {
    return artifactName;
  }

  public void setArtifactName(String artifactName) {
    this.artifactName = artifactName;
  }

  public MvnProperties consumerType(String consumerType) {
    this.consumerType = consumerType;
    return this;
  }

   /**
   * Get consumerType
   * @return consumerType
  **/
  @Schema(required = true, description = "")
  public String getConsumerType() {
    return consumerType;
  }

  public void setConsumerType(String consumerType) {
    this.consumerType = consumerType;
  }

  public MvnProperties producerType(String producerType) {
    this.producerType = producerType;
    return this;
  }

   /**
   * Get producerType
   * @return producerType
  **/
  @Schema(required = true, description = "")
  public String getProducerType() {
    return producerType;
  }

  public void setProducerType(String producerType) {
    this.producerType = producerType;
  }

  public MvnProperties consumerSpec(String consumerSpec) {
    this.consumerSpec = consumerSpec;
    return this;
  }

   /**
   * Get consumerSpec
   * @return consumerSpec
  **/
  @Schema(required = true, description = "")
  public String getConsumerSpec() {
    return consumerSpec;
  }

  public void setConsumerSpec(String consumerSpec) {
    this.consumerSpec = consumerSpec;
  }

  public MvnProperties producerSpec(String producerSpec) {
    this.producerSpec = producerSpec;
    return this;
  }

   /**
   * Get producerSpec
   * @return producerSpec
  **/
  @Schema(required = true, description = "")
  public String getProducerSpec() {
    return producerSpec;
  }

  public void setProducerSpec(String producerSpec) {
    this.producerSpec = producerSpec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MvnProperties mvnProperties = (MvnProperties) o;
    return Objects.equals(this.artifactVersion, mvnProperties.artifactVersion) &&
        Objects.equals(this.artifactGroupId, mvnProperties.artifactGroupId) &&
        Objects.equals(this.artifactPackage, mvnProperties.artifactPackage) &&
        Objects.equals(this.artifactName, mvnProperties.artifactName) &&
        Objects.equals(this.consumerType, mvnProperties.consumerType) &&
        Objects.equals(this.producerType, mvnProperties.producerType) &&
        Objects.equals(this.consumerSpec, mvnProperties.consumerSpec) &&
        Objects.equals(this.producerSpec, mvnProperties.producerSpec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactVersion, artifactGroupId, artifactPackage, artifactName, consumerType, producerType, consumerSpec, producerSpec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MvnProperties {\n");
    
    sb.append("    artifactVersion: ").append(toIndentedString(artifactVersion)).append("\n");
    sb.append("    artifactGroupId: ").append(toIndentedString(artifactGroupId)).append("\n");
    sb.append("    artifactPackage: ").append(toIndentedString(artifactPackage)).append("\n");
    sb.append("    artifactName: ").append(toIndentedString(artifactName)).append("\n");
    sb.append("    consumerType: ").append(toIndentedString(consumerType)).append("\n");
    sb.append("    producerType: ").append(toIndentedString(producerType)).append("\n");
    sb.append("    consumerSpec: ").append(toIndentedString(consumerSpec)).append("\n");
    sb.append("    producerSpec: ").append(toIndentedString(producerSpec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
